### ISSUE TITLE
GHC 8.10.1 compatibility

### ISSUE THREAD

**Issue by kirelagin** [dzhus/th-env#1]
Please, allow `template-haskell-2.16.*`. I am not sure, but I don’t think there are any incompatible changes in this version.

**Comment by dzhus** [comment]
@kirelagin Can you try th-env-0.1.0.2 please

**Comment by kirelagin** [comment]
I haven’t tried it myself yet, but I see that it succeeded on Hackage Matrix: https://matrix.hackage.haskell.org/#/package/th-env.
