### ISSUE TITLE
Add a variant of the envQ which fails at compile time if the env var is not defined

### ISSUE THREAD

**Issue by jhrcek** [dzhus/th-env#5]
It would be great if this lib provided a variant of envQ function that would fail at compile time if the environment variable is not defined (i.e. at the time when the TH splice is being evaluated) as opposed to returning Nothing. My use case: I want to hardwire value of environment variable provided at compile time into haskell binary - but don't want to have to deal with `Nothing` at runtime.
A variant of enQ like this (probably with better name than what I could think of on the spot) could look like this. Would you be willing to add something like this to this library?

```haskell
envQFailAtCompileTime :: IsString a => String -> SpliceQ a
envQFailAtCompileTime name =
    liftSplice $
        runIO (lookupEnv name) >>= \case
            Just v -> fromCode $ toCode [||fromString v||]
            Nothing -> fail $ "Environment variable " ++ name ++ " not defined"
```

**Comment by ggPeti** [comment]
@dzhus super lib! may I also ask you to include the compile time crash so that during runtime, there's no Nothing?

**Comment by dzhus** [comment]
`envQ'` perhaps?

**Comment by dzhus** [comment]
This should now be included in https://hackage.haskell.org/package/th-env-0.1.1

**Comment by jhrcek** [comment]
Thank you very much! :smile_cat:
